# Apparently this is the "official" way to silence NOTEs generated by R CMD check about symbols
# in pipelines which it misperceives as globals (https://github.com/tidyverse/magrittr/issues/29).
if(getRversion() >= "2.15.1")  utils::globalVariables(c('button_pressed','test_part','token'))

#' Process affect-grid task data file
#'
#' \code{affect_grid()} processes data files generated by the affect-grid task
#' (\url{https://earcanal.github.io/affect-grid/}).
#'
#'@examples
#'\dontrun{
#'}
#' @param path Path to data file
#' @param p Participant identifier
#' @keywords expfactory affect grid
#' @importFrom expfactory process_expfactory_experiment
#' @importFrom magrittr %>%
#' @importFrom dplyr filter select mutate
#' @export
#' @return Data frame
affect_grid <- function(path, p) {
  df <- expfactory::process_expfactory_experiment(path) %>%
    filter(test_part %in% c('response')) %>%
    mutate(cell = as.numeric(button_pressed)) %>%
    select('cell')

  # convert cell number to pleasure and arousal scores: -4 to +4
  arousal = 4 - (df$cell %/% 9)
  pleasure = (df$cell %% 9) - 4
  return(data.frame(arousal, pleasure))
}