# Apparently this is the "official" way to silence NOTEs generated by R CMD check about symbols
# in pipelines which it misperceives as globals (https://github.com/tidyverse/magrittr/issues/29).
if(getRversion() >= "2.15.1")  utils::globalVariables(c('button_pressed','test_part'))

#' Process affect-grid task data file
#'
#' \code{affect_grid()} processes data files generated by the affect-grid task
#' (\url{https://earcanal.github.io/affect-grid/}).
#'
#'@examples
#'\dontrun{
#'rsvp_df <- expand.grid(token = participants$token) %>%
#'  mutate(path=paste('data/', token, '_finished/rsvp-task-results.json', sep=''))
#'rsvp_df <- rsvp_df %>%
#'group_by(token) %>%
#'  do(., process_rsvp(.$path, .$token)) %>%
#'  ungroup %>%
#'  left_join(participants, by='token') %>%
#'  filter(phase == 'test', test_part == "response") %>%
#'  select(p, condition, trial_number, lag, correct, t1_correct, t2_correct, rt)
#'}
#' @param path Path to data file
#' @param p Participant identifier
#' @keywords expfactory affect grid
#' @importFrom expfactory process_expfactory_experiment
#' @importFrom magrittr %>%
#' @importFrom dplyr filter select mutate
#' @export
#' @return Data frame
affect_grid <- function(path, p) {
  expfactory::process_expfactory_experiment(path) %>%
    filter(test_part %in% c('response')) %>%
    select(p, button_pressed)
  
  # FIXME: cell -> score
  # pleasure -4 to +4
  # arousal -4 to +4
  
}